<?php


namespace app\modules\blog\controllers\actions;


use app\modules\blog\Module;
use Yii;
use yii\base\Action;
use yii\web\UnauthorizedHttpException;

class BaseAction extends Action
{
    public function beforeRun()
    {
        if (Yii::$app->user->isGuest) {
            throw new UnauthorizedHttpException(Module::t('blog', 'The request has not been applied because it lacks valid authentication credentials for the target resource'));
        }
        return parent::beforeRun(); // TODO: Change the autogenerated stub
    }
}